name: Create Release

on:
  push:
    branches:
      - main

jobs:
  runner:
    name: Runner
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/setup-node@v4

      - name: Check files and get content
        run: |
          FILES_COUNT=$(ls .changeset/pr-*.md | wc -l)

          if [ $FILES_COUNT -eq 0 ]; then
            echo "No changeset files found"
            exit 1
          fi

          if [ $FILES_COUNT -gt 1 ]; then
            echo "More than one changeset file found"
            exit 1
          fi

          if [ ! -d "releases" ]; then
            mkdir releases
          fi

          FILE=$(basename $(ls .changeset/pr-*.md))
          echo "RELEASE_FILE=$FILE" >> $GITHUB_ENV
  
          cp .changeset/$FILE releases/$FILE
          
          CONTENT=$(cat ".changeset/$FILE")
          if [ -z "$CONTENT" ]; then
            echo "Changeset file is empty"
            exit 1
          fi

          echo "RELEASE_CONTENT=$CONTENT" >> $GITHUB_ENV
      
      - name: Bump up version
        run: |
          npm install --omit=dev
          npx changeset version
          npx changeset tag

          TAG=$(git tag --sort=taggerdate | tail -1)
          if [ -z "$TAG" ]; then
            echo "No git tags found"
            exit 1
          fi
          echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV

      - name: Commit and push markdown file to current branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Bump up version"
          git push origin main
          git push origin --tags

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_TAG }}
          body: ${{ env.RELEASE_CONTENT }}

      