name: Create Release

on:
  push:
    branches:
      - main

jobs:
  runner:
    name: Runner
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/setup-node@v4

      - name: Check files and copy to releases folder
        run: |
          FILES_COUNT=$(ls .changeset/pr-*.md | wc -l)

          if [ $FILES_COUNT -eq 0 ]; then
            echo "No changeset files found"
            exit 1
          fi

          if [ $FILES_COUNT -gt 1 ]; then
            echo "More than one changeset file found"
            exit 1
          fi

          if [ ! -d "releases" ]; then
            mkdir releases
          fi

          FILE=$(basename $(ls .changeset/pr-*.md))

          if [ -z "$FILE" ]; then
            echo "No changeset file found"
            exit 1
          fi

          echo "RELEASE_FILE=$FILE" >> $GITHUB_ENV
  
          cp .changeset/$FILE releases/$FILE
      
      - name: Bump up version
        run: |
          npm install --omit=dev
          npx changeset version
          npx changeset tag

      - name: Commit and push markdown file to current branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Bump up version"
          git push origin main
          git push origin --tags

      - name: Create Release
        id: release
        run: |
          TAG=$(node -p "require('./package.json').version")
          echo "RELEASE_TAG=v$TAG" >> $GITHUB_ENV

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_TAG }}
          bodyFile: releases/${{ env.RELEASE_FILE }}

      