name: Create Release

on:
  push:
    branches:
      - main

jobs:
  runner:
    name: Runner
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/setup-node@v4

      - name: Check files and get content
        run: |
          FILES=$(ls .changeset/pr-*.md)

          if [ ${#FILES[@]} -eq 0 ]; then
            echo "No changeset files found"
            exit 1
          fi

          if [ ${#FILES[@]} -gt 1 ]; then
            echo "More than one changeset file found"
            exit 1
          fi

          if [ ! -d "releases" ]; then
            mkdir releases
          fi

          FILE=$(basename $FILES)
          echo "RELEASE_FILE=$FILE" >> $GITHUB_ENV
  
          cp .changeset/$FILE releases/$FILE
          echo "RELEASE_CONTENT=$(cat releases/$FILE)" >> $GITHUB_ENV
      
      - name: Bump up version
        run: |
          npm install --omit=dev
          npx changeset version
          npx changeset tag
          echo "RELEASE_TAG=$( git tag --sort=taggerdate | tail -1 )" >> $GITHUB_ENV

      - name: Commit and push markdown file to current branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Bump up version"
          git push origin main --follow-tags

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_TAG }}
          body: ${{ env.RELEASE_CONTENT }}

      