# This is a basic workflow to help you get started with Actions

name: Create Release

# Controls when the action will run.
on:
  release:
    types: [created]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build runner
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Algo
        run: echo "hello world"