name: Create Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build runner
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v4
      
      # Fetch release content
      - name: Get release info
        id: release-info
        run: |
          echo "Release tag: $(jq -r '.release.tag_name' $GITHUB_EVENT_PATH)"
          echo "Release body: $(jq -r '.release.body' $GITHUB_EVENT_PATH)"
          echo "Release name: $(jq -r '.release.name' $GITHUB_EVENT_PATH)"

      # Optionally, use the fetched release info in further steps
      - name: Use release info
        run: |
          echo "Using release tag: ${{ steps.release-info.outputs.tag_name }}"
