name: PR to Markdown

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  create-markdown:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4

    - name: Get PR details
      id: pr_details
      run: |
        PR_TITLE=${{ github.event.pull_request.title }}
        PR_BODY=${{ github.event.pull_request.body }}
        PR_BRANCH=${{ github.event.pull_request.head.ref }}

    - name: Create Markdown file
      run: |
        VERSION_BUMP=$(PR_TITLE node -p "process.env.PR_TITLE.split('|')[0].replaceAll(/\W/g, '').toLowerCase()")
        PACKAGE_NAME=$(node -p "require('./package.json').name")
        FILENAME="pr-${{ github.event.number }}.md"
        FILEPATH=".changeset/$FILENAME"
        echo "---" > $FILENAME
        echo "\"$PACKAGE_NAME\": $VERSION_BUMP" >> $FILENAME
        echo "---" >> $FILENAME
        echo "# ${{ env.PR_TITLE }}" >> $FILENAME        
        echo "" >> $FILENAME
        echo "${{ env.PR_BODY }}" >> $FILENAME

    - name: Commit and push markdown file to current branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout ${{ env.PR_BRANCH }}
        git add pr-${{ github.event.number }}.md
        git commit -m "Add PR #${{ github.event.number }} details"
        git push origin ${{ env.PR_BRANCH }}
